import { Resend } from 'resend';
import nodemailer from 'nodemailer';

const resend = new Resend(process.env.RESEND_API_KEY);

// SMTP Transporter for fallback or specific use cases
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: process.env.SMTP_SECURE === 'true',
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

const APP_NAME = "Sehati";
const APP_COLOR = "#3B82F6"; // Modern Blue

const emailLayout = (content: string) => `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1F2937; margin: 0; padding: 0; background-color: #F9FAFB; }
    .container { max-width: 600px; margin: 20px auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); border: 1px solid #E5E7EB; }
    .header { background-color: ${APP_COLOR}; padding: 32px 20px; text-align: center; }
    .header h1 { color: #ffffff; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.025em; }
    .content { padding: 40px 32px; }
    .footer { padding: 24px; text-align: center; font-size: 12px; color: #6B7280; background: #F3F4F6; }
    .button { display: inline-block; padding: 12px 24px; background-color: ${APP_COLOR}; color: #ffffff; text-decoration: none; border-radius: 8px; font-weight: 600; margin-top: 24px; }
    .card { background: #F9FAFB; border: 1px solid #F3F4F6; border-radius: 12px; padding: 20px; margin-top: 20px; }
    .stat-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #E5E7EB; }
    .stat-row:last-child { border-bottom: none; }
    .stat-label { font-weight: 500; color: #4B5563; }
    .stat-value { font-weight: 700; color: ${APP_COLOR}; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${APP_NAME} <span style="font-weight: 300; opacity: 0.8;">Health</span></h1>
    </div>
    <div class="content">
      ${content}
    </div>
    <div class="footer">
      &copy; ${new Date().getFullYear()} ${APP_NAME} AI Health Platform. All rights reserved.<br/>
      Improving lives through contactless monitoring and predictive analysis.
    </div>
  </div>
</body>
</html>
`;

export const sendWelcomeEmail = async (email: string, firstName: string) => {
  const html = emailLayout(`
    <h2 style="font-size: 20px; color: #111827; margin-bottom: 16px;">Welcome to the future of health, ${firstName}!</h2>
    <p>We're thrilled to have you join <strong>Sehati</strong>. Your account has been successfully created and you're now part of a community leveraging advanced AI to monitor and protect their health.</p>
    <p>With Sehati, you can:</p>
    <ul style="padding-left: 20px;">
      <li>Monitor heart rate contactlessly using just your camera.</li>
      <li>Get AI-powered diabetes risk assessments.</li>
      <li>Sync with native health data from Apple Health and Google Health Connect.</li>
    </ul>
    <a href="${process.env.NEXTAUTH_URL}/profile" class="button">Go to your Dashboard</a>
  `);

  try {
    // Try Resend first
    await resend.emails.send({
      from: `Sehati Health <${process.env.SMTP_USER}>`,
      to: [email],
      subject: 'Welcome to Sehati Health AI',
      html: html,
    });
  } catch (error) {
    // Fallback to SMTP
    console.error("Resend failed, falling back to SMTP:", error);
    await transporter.sendMail({
      from: `"Sehati" <${process.env.SMTP_USER}>`,
      to: email,
      subject: 'Welcome to Sehati Health AI',
      html: html,
    });
  }
};

export const sendPredictionEmail = async (email: string, firstName: string, predictionData: any) => {
  const riskColor = predictionData.riskScore > 50 ? "#EF4444" : (predictionData.riskScore > 20 ? "#F59E0B" : "#10B981");
  
  const html = emailLayout(`
    <h2 style="font-size: 20px; color: #111827; margin-bottom: 16px;">New AI Health Assessment Ready</h2>
    <p>Hello ${firstName}, your latest health prediction report has been generated by our AI engine.</p>
    
    <div class="card">
      <div style="text-align: center; margin-bottom: 20px;">
        <div style="font-size: 14px; text-transform: uppercase; letter-spacing: 0.1em; color: #6B7280;">Risk Assessment</div>
        <div style="font-size: 32px; font-weight: 800; color: ${riskColor};">${predictionData.riskLabel || 'Processed'}</div>
      </div>
      
      <div class="stat-row">
        <span class="stat-label">Diabetes Risk Score</span>
        <span class="stat-value">${predictionData.riskScore}%</span>
      </div>
      <div class="stat-row">
        <span class="stat-label">Analysis Date</span>
        <span class="stat-value">${new Date().toLocaleDateString()}</span>
      </div>
    </div>
    
    <p style="margin-top: 24px; font-size: 14px; color: #6B7280; font-style: italic;">
      Note: This is an AI-generated assessment and should not replace professional medical advice. Always consult with a doctor regarding your health concerns.
    </p>
    
    <a href="${process.env.NEXTAUTH_URL}/profile" class="button">View Detailed Report</a>
  `);

  try {
    await resend.emails.send({
      from: `Sehati Health <${process.env.SMTP_USER}>`,
      to: [email],
      subject: 'Your Sehati AI Health Report',
      html: html,
    });
  } catch (error) {
    await transporter.sendMail({
      from: `"Sehati" <${process.env.SMTP_USER}>`,
      to: email,
      subject: 'Your Sehati AI Health Report',
      html: html,
    });
  }
};

export const sendContactEmail = async (formData: {
  name: string;
  email: string;
  subject: string;
  message: string;
}) => {
  const html = emailLayout(`
    <h2 style="font-size: 20px; color: #111827; margin-bottom: 16px; font-weight: 700;">New Contact Inquiry</h2>
    <p style="color: #4B5563; margin-bottom: 24px;">You have received a new message through the Sehati contact form. Here are the details:</p>
    
    <div style="background: #F9FAFB; border: 1px solid #E5E7EB; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td style="padding: 8px 0; font-size: 14px; color: #6B7280; width: 100px; font-weight: 600;">Sender:</td>
          <td style="padding: 8px 0; font-size: 14px; color: #111827; font-weight: 700;">${formData.name}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-size: 14px; color: #6B7280; font-weight: 600;">Email:</td>
          <td style="padding: 8px 0; font-size: 14px; color: #3B82F6; font-weight: 600;">${formData.email}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-size: 14px; color: #6B7280; font-weight: 600;">Subject:</td>
          <td style="padding: 8px 0; font-size: 14px; color: #111827; font-weight: 600;">${formData.subject}</td>
        </tr>
      </table>
    </div>

    <div style="margin-top: 24px;">
      <h3 style="font-size: 16px; color: #111827; margin-bottom: 12px; font-weight: 700;">Message Body</h3>
      <div style="background: #ffffff; padding: 20px; border-radius: 12px; border: 1px solid #E5E7EB; color: #374151; line-height: 1.7; font-size: 15px; box-shadow: inset 0 2px 4px rgba(0,0,0,0.02);">
        ${formData.message.replace(/\n/g, '<br/>')}
      </div>
    </div>
    
    <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #E5E7EB; text-align: center;">
      <p style="font-size: 13px; color: #9CA3AF;">
        This is an automated notification from your Sehati Platform.
      </p>
    </div>
  `);

  const mailOptions = {
    from: `"Sehati Contact" <${process.env.SMTP_USER}>`,
    to: 'younessbakkali09@gmail.com',
    replyTo: formData.email,
    subject: `Contact Form: ${formData.subject}`,
    html: html,
  };

  try {
    // Try SMTP for this one as it's an internal notification
    await transporter.sendMail(mailOptions);
  } catch (error) {
    console.error("SMTP contact email failed:", error);
    // Try Resend as backup
    await resend.emails.send({
      from: `Sehati Contact <${process.env.SMTP_USER}>`,
      to: ['younessbakkali09@gmail.com'],
      replyTo: formData.email,
      subject: `Contact Form: ${formData.subject}`,
      html: html,
    });
  }
};
